name: CI

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install and run Luacheck
      uses: nebularg/actions-luacheck@v1
      with:
        args: "--no-color -q"

    - name: Create Package
      uses: BigWigsMods/packager@master
      env:
        GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

